services:
  users.webapi:
    image: users.webapi
    build:
      context: .
      dockerfile: Users.WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlpreview
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=${BD_HOST_MSSQL},${DB_PORT};Database=${DB_DATABASE};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True

  sqlpreview:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlpreview
    hostname: sqlpreview
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local
