services:
  users.webapi:
    image: users.webapi
    build:
      context: .
      dockerfile: Users.WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlpreview
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlpreview,1433;Database=${DB_DATABASE};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True
    networks:
      - external_network  # <-- Se conecta a la red externa

  sqlpreview:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlpreview
    hostname: sqlpreview
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - external_network  # <-- Se conecta a la red externa

volumes:
  sql_data:
    driver: local

networks:
  external_network:
    name: my_external_network  # Nombre real de la red
    external: true
